### PR TITLE
tags were not created

### PR DESCRIPTION
**Pull request by Mapel88**
received the following warnings:
[WARNING ] Requested grain 'roles' is not available on minion: nl1-stgjob03
[WARNING ] Requested grain 'environment' is not available on minion: nl1-stgjob03
[WARNING ] Requested grain 'region' is not available on minion: nl1-stgjob03

Even though they exists and attributes are created properly.

### CODE REVIEW

**Comment by amendlik** [comment]
This patch removes every blank line from the file. Could you update your PR to include only the changes relevant to the issue?

**Comment by amendlik** [comment]
@Mapel88 Can you provide a listing of the grains on the servers where it is not working?

**Comment by Mapel88** [comment]
Sorry for my late response.
It didn't work for the grains mentioned in the warning. Didn't test other grains.

**Comment by amendlik** [comment]
@Mapel88 What didn't work?

Can you just run `grains.items` on the minions reporting the errors? You can remove any sensitive information before posting, but I'd like to see that the grains do exist and what values they hold.

Also, for your patch - can you squash those and do a force push. We still don't have a single commit that clearly shows what you want to change.

**Comment by Mapel88** [comment]
All minions returned this warning.
The grains exists and are added as attributes properly.
I'm closing this PR and creating a new one.

**Comment by amendlik** [comment]
@Mapel88 There is on need to create a new PR. You can just "force push" to your existing branch an overwrite anything that is there.

Let's first focus on helping me understand the problem you're seeing. Can you show me what grains you have, and what args are you passing to SaltGenResource?

**Comment by Mapel88** [comment]
Hi,
Sorry for the mess, I'm not very experienced with git, and I edited the code directly in gitHub, so no force push in the UI.
I created a new PR with the details you requested.

**Pull request closed without merging**
